spring.application.name=understand-spring-boot-actuator
server.port=8081
spring.main.banner-mode=off
# *** Note. multiple loggers level will work if you add logback.xml file
logging.level.root[0]=info
logging.level.root[1]=debug

# *** Note!! This line below it affects hasRole(...) in spring security config it didn't work use @RequestMapping("/api") instead
# Set main prefix of servlet or res controller
# So now when you access actuator endpoints you have to tru below as /api/actuator/health
# server.servlet.context-path=/api

# If you want to change /actuator to other word set it on *** management.endpoints.web.base-path
# Will be http://localhost:8081/api/admin/***
management.endpoints.web.base-path=/api/admin
# Change actuator's name endpoint as /info to /info_application
# Will be http://localhost:8081/api/admin/info_application
management.endpoints.web.path-mapping.info=info_application
# Open all features endpoint spring boot actuator
management.endpoints.web.exposure.include=*
# *** Now actuator/health => will give more details because i set management.endpoint.health.show-details=always. As status of database / disk space , ...
management.endpoint.health.show-details=always
# *** Open actuator/info by default will be null
management.info.env.enabled=true
# We can set it by info.app.**
info.app.name=understand-spring-boot-actuator
info.app.servlet.context.port=8081
info.app.management.actuator.port=8081
info.app.version=1.0
info.app.developer.github=github.com/thitikorn-nupan
info.app.developer.linkedin=linkedin.com/in/thitikorn-nupan
# localhost:8081/api/admin/info_application
#"app": {
#     "name": "understand-spring-boot-actuator",
#     "servlet": {
#           "context": {
#               "port": "8081"
#            }
#      },
#      "management": {
#            "actuator": {
#               "port": "8081"
#            }
#       },
#       "version": "1.0",
#       "developer": {
#           "github": "github.com/thitikorn-nupan",
#           "linkedin": "linkedin.com/in/thitikorn-nupan"
#           "linkedin": "linkedin.com/in/thitikorn-nupan"
#        }
#}

# *** actuator/loggers => show logs of systems
# *** Spring Boot Actuator shows endpoints of systems
# *** it's good for hacker so you need to use Spring Boot Security to help for Authorized before access actuator endpoints

